name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository' 
        uses: actions/checkout@v3
      - name: Set up GraalVM Native Image toolchain
        uses: helpermethod/graalvm-native-image-toolchain@0.0.2
        with:
          graalvm-version: 22.3.0
          java-version: 11
#       - uses: graalvm/setup-graalvm@v1 
#         with:
#           version: 'latest'
#           java-version: '11'
#           components: 'native-image'
#           github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Cache Maven packages'
        uses: actions/cache@v3.0.11
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: 'Build'  
        run: |
          mvn -B --file pom.xml verify -Pnative -Dquarkus.native.additional-build-args=-H:-UseContainerSupport
          cd ./target
          ls
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push 
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: true
          file: src/main/docker/Dockerfile.native
          tags: nithyathulasiraman/graalvm-native-build-app:latest
